version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - citus

  citus_master:
    image: citusdata/citus:10.2
    container_name: citus_master
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    depends_on:
      - citus_worker_1
    networks:
      - citus

  citus_worker_1:
    image: citusdata/citus:10.2
    container_name: citus_worker_1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - citus
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@citus_master:5432/mydatabase?schema=public"
    deploy:
      update_config:
          parallelism: 2
          delay: 10s
    networks:
      - citus

networks:
  citus:
    driver: bridge